// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4SqdR8BnJobqX_WfsLl_D3sz5TqXeLlE',
    appId: '1:293662858269:web:848a33c98f8a0e807fbaf4',
    messagingSenderId: '293662858269',
    projectId: 'aegismind-17a11',
    authDomain: 'aegismind-17a11.firebaseapp.com',
    storageBucket: 'aegismind-17a11.firebasestorage.app',
    measurementId: 'G-JP7XTDEMW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxtYU5I2enge2xrjE7ikmd0vZgvRWp2QY',
    appId: '1:293662858269:android:f4a4b276b23d12517fbaf4',
    messagingSenderId: '293662858269',
    projectId: 'aegismind-17a11',
    storageBucket: 'aegismind-17a11.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4SqdR8BnJobqX_WfsLl_D3sz5TqXeLlE',
    appId: '1:293662858269:web:8e8afb44076f2fbc7fbaf4',
    messagingSenderId: '293662858269',
    projectId: 'aegismind-17a11',
    authDomain: 'aegismind-17a11.firebaseapp.com',
    storageBucket: 'aegismind-17a11.firebasestorage.app',
    measurementId: 'G-BN7P2KTBLE',
  );
}
